# Generated by Django 4.1.7 on 2023-03-24 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('number_of_pages', models.IntegerField()),
                ('resume', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Literary_genres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.book')),
                ('client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.client')),
                ('library_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.library')),
            ],
        ),
        migrations.CreateModel(
            name='Books_at_library',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_stock', models.IntegerField()),
                ('number_of_borrowed_books', models.IntegerField(default=0)),
                ('book_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.book')),
                ('library_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.library')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='literary_genre_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.literary_genres'),
        ),
    ]
