# Generated by Django 4.1.7 on 2023-03-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='senha',
            new_name='password',
        ),
    ]
