# Generated by Django 4.1.7 on 2023-04-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0002_rename_senha_library_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='literary_genre_fk',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='resume',
        ),
        migrations.DeleteModel(
            name='Literary_genres',
        ),
    ]
