# Generated by Django 4.1.7 on 2023-04-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0004_alter_borrow_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='procedencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tombo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
