# Generated by Django 4.1.7 on 2023-05-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0005_book_data_book_especie_book_procedencia_book_tombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='library_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Libraryapp.library'),
        ),
    ]
