# Generated by Django 4.1.7 on 2023-11-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libraryapp', '0006_client_library_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('forum', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('commentText', models.CharField(max_length=2000)),
            ],
        ),
    ]
